fix sent_prefixes if not advertising using send-state
napalm-automation/napalm-junos pull request #209
Opened 2017-09-29 08:43 UTC by ckishimo

While running `get_bgp_neighbors()` I was getting the following error:
```
Traceback (most recent call last):
  File "client_junos_bgp.py", line 21, in <module>
    res = dev.get_bgp_neighbors()
  File "/home/ckishimo/python/napalm-junos/napalm_junos/junos.py", line 595, in get_bgp_neighbors
    uptime_table_items=uptime_table_items)
  File "/home/ckishimo/python/napalm-junos/napalm_junos/junos.py", line 561, in _get_bgp_neighbors_core
    peer['address_family'] = self._parse_route_stats(neighbor_details)
  File "/home/ckishimo/python/napalm-junos/napalm_junos/junos.py", line 475, in _parse_route_stats
    data[family]['sent_prefixes'] = neighbor['sent_prefixes'][idx]
IndexError: list index out of range
```
It seems not all ribs have the node `<advertised-prefix-count>`. The only way I found to fix that was to use the `send-state` node which can have as a value `in sync` or `not advertising`. So if `send-state == 'not advertising'` the `<advertised-prefix-count>` may not exist, so we can count it as zero. Example:
```
             <bgp-rib junos:style="detail">
                <name>bgp.evpn.0</name>
                <bgp-rib-state>BGP restart is complete</bgp-rib-state>
                <vpn-rib-state>VPN restart is complete</vpn-rib-state>
                <send-state>not advertising</send-state>
                <active-prefix-count>1</active-prefix-count>
                <received-prefix-count>1</received-prefix-count>
                <accepted-prefix-count>1</accepted-prefix-count>
                <suppressed-prefix-count>0</suppressed-prefix-count>
            </bgp-rib>
```
Please let me know if that makes sense

2017-09-29 09:27 UTC, mirceaulinic approved these changes
Looks good. Thanks!

2017-09-29 09:28 UTC, mirceaulinic commented
@ckishimo would you be able to provide a test case for this? And does this solve https://github.com/napalm-automation/napalm-junos/issues/177?

2017-09-29 09:42 UTC, ckishimo commented
@mirceaulinic for the test case is it enough to create a new dir in `mocked_data/test_get_bgp_neighbors` with the xml file and the expected_result.json ?
I'll have a look to #177 
Thanks!

2017-09-29 09:47 UTC, mirceaulinic commented
Yes @ckishimo - you have to create a new dir under `mocked_data/test_get_bgp_neighbors`, where you put the `expected_results.json`, and a file with explicit `fact.yml` (as the output may be different across versions and platforms) + a couple of XML documents, as in https://github.com/napalm-automation/napalm-junos/tree/develop/test/unit/mocked_data/test_get_bgp_neighbors/normal.

2017-09-29 14:57 UTC, mirceaulinic requested changes
One more small change requested, then we're good to go!

2017-09-29 14:57 UTC, mirceaulinic commented on test/unit/mocked_data/test_get_bgp_neighbors/use-send-state-pr209/get-bgp-neighbor-information.xml
> +    <bgp-peer junos:style="detail">
To make sure this will pass the tests, we must avoid the junos namespace, so please remove the `junos:` from everywhere.

2017-09-29 15:19 UTC, mirceaulinic commented on test/unit/mocked_data/test_get_bgp_neighbors/use-send-state-pr209/get-bgp-neighbor-information.xml
> +    <bgp-peerstyle="detail">
Erm - too much removed: make sure you leave the space, i.e., `bgp-peer style="detail"` etc.

2017-10-03 12:16 UTC, mirceaulinic requested changes
Hi @ckishimo - there's one more mock file to provide for the new test case: `get-instance-information.xml`. Thanks!

2017-10-03 17:17 UTC, mirceaulinic commented
One (or maybe few more) @ckishimo - `get-bgp-neighbor-informationmaster.xml` this time; but have a look at https://github.com/napalm-automation/napalm-junos/tree/develop/test/unit/mocked_data/test_get_bgp_neighbors/normal and make sure you have the same files (with the content you want to provide).

2017-10-04 10:05 UTC, ckishimo commented
@mirceaulinic sorry I thought not all files were needed. I will push same files as in the `normal` directory

2017-10-10 09:39 UTC, mirceaulinic approved these changes
Yaaay

2017-10-10 09:39 UTC, merged

2017-10-10 09:40 UTC, mirceaulinic commented
Thanks @ckishimo