Implementation of method ping()
napalm-automation/napalm-junos pull request #97
Opened 2016-12-25 00:58 UTC by pkleanthous

This PR aim to provide the implementation of ping() method on Junos Devices.

It follows the guidelines for the method that you can find here: [napalm.readthedocs.io](http://napalm.readthedocs.io/en/latest/base.html)

In Junos, we use the `interface` switch to define the source interface of echo request as it does not support out of box ip address.

```
> ping interface ?
Possible completions:
  <interface>          Source interface (multicast, all-ones, unrouted packets)
```

More info about `ping` command at [Juniper Documentation](https://www.juniper.net/documentation/en_US/junos12.1x47/topics/task/operational/security-ping-command-using.html)

2016-12-25 10:22 UTC, dbarrosop commented
Great job @pkleanthous! I think everything is fine but I will leave the approval to @mirceaulinic as he has more experience with this sort of operations in JunOS devices.

2016-12-25 15:05 UTC, mirceaulinic requested changes
Thanks @pkleanthous!

It looks good on the surface - but I will make some tests later next week. Meanwhile, please apply the following changes:

- `source` arg, commented also inline
- wherever you have <object>.findtext replace it with the napalm-base helper `find_txt`: https://github.com/napalm-automation/napalm-base/blob/develop/napalm_base/helpers.py#L142
Example:  `probe_summary.findtext("rtt-minimum")` would be replaced with `napalm_base.helpers.find_txt(probe_summary, 'rtt-minimum')` - the advantage being that will give you empty string instead of `None` in case the tag does not exist, which would lead to unwanted exceptions
- Similarly, please use the `convert` helper: https://github.com/napalm-automation/napalm-base/blob/develop/napalm_base/helpers.py#L166 when casting data. Example: `int(<object>)`  --> `napalm_base.helpers.convert(int, <object>, 100)` which will return you 100 if <object> cannot be converted / is None etc.

2016-12-25 15:05 UTC, mirceaulinic commented on napalm_junos/junos.py
> +            source_str = 'interface {source}'.format(source=source)
Here should be `source_str = 'source {source}'.format(source=source)` instead - the `source` arg is accepted.

2016-12-25 18:31 UTC, pkleanthous commented
Hi @dbarrosop & @mirceaulinic. Thanks for the review.

I just made the requested changes.

2016-12-26 05:08 UTC, mirceaulinic approved these changes

2016-12-26 10:13 UTC, XioNoX commented
fwiw, I tried this pull request with the new validation class/framework (through napalm_validate).
Everything worked well!

With a valid destination IP:
```
 'ping': {u'complies': True,
          u'extra': [],
          u'missing': [],
          u'present': {'success': {u'complies': True, u'nested': True}}}}
```
With an invalid destination IP:
```
 'ping': {u'complies': False,
          u'extra': [],
          u'missing': ['success'],
          u'present': {}}}
```

2016-12-28 14:42 UTC, merged