Convert to TOX; fixing set of Python3 issues
napalm-automation/napalm-junos pull request #98
Opened 2016-12-26 09:00 UTC by ktbyers

This doesn't fix all of the Python3 issues, just some of them.

Still more work to do on the others.

2016-12-26 09:04 UTC, ktbyers commented
@ogenstad Can you double check the TOX items?

2016-12-26 09:28 UTC, ktbyers commented
Issues I need to fix...so closing PR.

2016-12-26 10:01 UTC, ktbyers commented
Having test issues...closing for now. Need to research more why failing.

2016-12-26 10:32 UTC, ogenstad commented
@ktbyers don't think tox is related to the failures. By just looking briefly I would guess that this is the issue:
https://github.com/napalm-automation/napalm-junos/blob/develop/napalm_junos/junos.py#L1358-L1361 and that the unordered dict returns different data on different runs. So some times the tests are searching for a file which doesn't exist.

get_config__format_text__database_candidate.xml instead of 
get_config__database_candidate__format_text.xml

2016-12-27 03:31 UTC, ktbyers commented
@ogenstad Yes, I don't think it is TOX related either. 

I am getting different errors on my test server and errors under Python2...so I was going to go sort some of that out and resubmit.

2016-12-27 04:13 UTC, ktbyers commented
@mirceaulinic I fixed the issues I was having with get_config tests and dictionary ordering. 

Is this 'blocked' for some other reason?

2016-12-27 20:28 UTC, ktbyers commented
@mirceaulinic @dbarrosop Note, for junos_views.py fix. I think this should really be fixed in PYEZ and submitted an issue there. I implemented the current fix as an interim solution.

2016-12-27 22:44 UTC, ktbyers commented on napalm_junos/junos.py
> +            rv['running'] = py23_compat.text_type(config.text)
@mirceaulinic Do you see any reason we need the .encode('ascii', 'replace') here?

config.text is already a 'str' in Python2.

The encode('ascii', 'replace') causes an issue in Python3 in that it gets me back a byte-string and not a Python3 unicode string (i.e. I would have to go and decode the string).

2016-12-27 22:45 UTC, ktbyers commented
@mirceaulinic We should also regression test this against real Juniper device.

2016-12-28 05:47 UTC, mirceaulinic commented
Sure @ktbyers - I will do some tests later today.

2016-12-28 07:03 UTC, mirceaulinic requested changes
This looks good, except the duplicate YAML file.

2016-12-28 07:03 UTC, mirceaulinic commented on napalm_junos/utils/junos_views.py
> +if py23_compat.PY2:
Please let's not have two separate files - not only that it's redundant, but also will be harder to maintain.

Till junos-eznc will provide the necessary features, we can do:

```
_YAML_ = splitext(__file__)[0] + '.yml'
_junos_views = loadyaml(_YAML_)
if py23_compat.PY3:
    for obj_name, obj in _junos_views.items():
        if not hasattr(obj, 'FIELDS'):
            # it's a table not a view
            continue
        for field_name, field_props in obj.FIELDS.items():
            if field_props.get('astype') == unicode:
                field_props['astype'] = str
globals().update(_junos_views)
```

Which goes through the views and replaces unicodes with text, _only_ when PY3.

2016-12-28 18:44 UTC, ktbyers commented on napalm_junos/utils/junos_views.py
> +if py23_compat.PY2:
I am happy for another solution, but the above won't work. It will fail on the 

```
_junos_views = loadyaml(_YAML_)

2016-12-28 18:48 UTC, mirceaulinic commented on napalm_junos/utils/junos_views.py
> +if py23_compat.PY2:
So I was looking into https://github.com/Juniper/py-junos-eznc/issues/639:

`Under python2, astype will correctly be matched as opt will be 'unicode', but this will be None under Python3.`

And it's not clear to me if `loadyaml` raises exception, or it just does not take the right `astype`?

2016-12-28 18:49 UTC, ktbyers commented on napalm_junos/utils/junos_views.py
> +if py23_compat.PY2:
Okay, I think I have a workaround for it...let me test it.

2016-12-28 19:29 UTC, mirceaulinic approved these changes

2016-12-28 19:33 UTC, ktbyers commented on napalm_junos/utils/junos_views.py
> +if py23_compat.PY2:
Yes, it raises an exception (line 121 here):

https://github.com/Juniper/py-junos-eznc/blob/master/lib/jnpr/junos/factory/factory_loader.py

2016-12-28 19:35 UTC, merged